config/routes.rb
Rails.application.routes.draw do

  resources :reviews

  root 'welcome#index'
  resources :movies

  resources :orders, except: [:new, :show]
  get '/genres' => 'movies#genres', as: :genres
  get '/movielist' => 'movies#show_genres'
  get '/orders/new/:id' => 'orders#new', as: :buy_movie
  get '/orders/cart/:id' => 'orders#show', as: :show_orders
  get '/cart/finalize/:sum' => 'orders#finalize', as: :finalize_order
  get '/cart/pay/:id' => 'orders#delegate_transaction', as: :delegate_order
  get '/watchlist' => 'orders#watchlist', as: :watch
  post '/watchlistpayu' => 'orders#watchlist'
  get '/theater/:movie' => 'orders#watch', as: :theater

  resources :orders

  devise_for :users, :controllers => { registrations: 'registrations' }

  resources :users

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]

  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.all
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
    @review = Review.new
    @user_reviews = @movie.reviews
  end
  def genres

  end
  def show_genres
    @movies = Movie.all.where(genre: params[:genre])
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(:title, :description, :rating, :cast, :photo, :price, :video, :genre)
    end
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/movies/_form.html.erb
<%= form_for(@movie) do |f| %>
<div class="form-group">
  <% if @movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% @movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title, class:"form-control" %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description, class:"form-control" %>
  </div>
  <div class="field">
    <%= f.label :rating %><br>
    <%= f.number_field :rating, class:"form-control" %>
  </div>
      <div class="field">
        <%= f.label :price %><br>
        <%= f.text_field :price, class:"form-control" %>
      </div>
  <div class="field">
    <%= f.label :cast %><br>
    <%= f.text_area :cast, class:"form-control" %>
  </div>

    <div class="field">
      <%= f.label :okladka %><br>
    <%= f.file_field :photo, class:'file', class:"form-control" %>
    </div>
    <div class="field">
      <%= f.label :gatunek %><br>
      <%= f.select(:genre, options_for_select([['Horror','horror'],['Komedia','komedia'],['Fantasy','fantasy'],['SciFi','scifi']]), class:"form-control") %>
    </div>
    <div class="field">
      <%= f.label :film %><br>
      <%= f.file_field :video %>
    </div>

  <div class="actions">
    <%= f.submit %>
  </div>
        </div>
    </div>
<% end %>

app/views/movies/edit.html.erb
<h1>Editing Movie</h1>

<%= render 'form' %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/movies/genres.html.erb
<%= link_to 'Horror', :controller => "movies", :action => "show_genres", :genre => "horror" %>
<%= link_to 'Komedia', :controller => "movies", :action => "show_genres", :genre => "komedia" %>
<%= link_to 'Fantasy', :controller => "movies", :action => "show_genres", :genre => "fantasy" %>
<%= link_to 'SciFi', :controller => "movies", :action => "show_genres", :genre => "scifi" %>

app/views/movies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Movies</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Rating</th>
      <th>Cast</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @movies.each do |movie| %>
      <tr>
        <td><%= movie.title %></td>
        <td><%= movie.description %></td>
        <td><%= movie.rating %></td>
        <td><%= movie.cast %></td>
        <td><%= link_to 'Show', movie %></td>
        <td><%= link_to 'Edit', edit_movie_path(movie) %></td>
        <td><%= link_to 'Destroy', movie, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Movie', new_movie_path %>

app/views/movies/new.html.erb
<h1>New Movie</h1>

<%= render 'form' %>

<%= link_to 'Back', movies_path %>

app/views/movies/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row">


  <div class="col-md-5-offset">
    <%= image_tag @movie.photo.url, size:'280' %>
    </div>
  <div class="col-md-4-offset-1">
  <strong>Tytuł:</strong>
  <%= @movie.title %>,

  <strong>Ocena:</strong>

  <% @movie.rating.times do %>
        <span class="star" aria-hidden="true"></span>
        <% end %>,

  <strong>Cena:</strong>
  <%= @movie.price %> zł,

  <strong>Gatunek:</strong>
  <%= @movie.genre %><br>

  <strong>Obsada:</strong><br>
  <%= simple_format @movie.cast.tr(",","\n") %>

  </div>
  </div>
  <div class="row">
    <div class="col-md-3-offset">
    <strong>Opis:</strong><br>
    <%= @movie.description %>
  </div>
    <%= link_to 'Złóż zamówienie', buy_movie_path(@movie.id), class: "btn btn-lg" %>
    </div>


<div class="row">
  <div class="col-md-3-offset">
<%= render 'reviews/form' %>
    </div></div>
    Oceny użytkowników:<br>

    <% @user_reviews.each do |review| %>
    <div class="row">
      <div class="col-md-3-offset">
        <%= image_tag avatar_url(review.user) %>
        <%= review.description %>
        <% review.rating.times do %>
            <span class="star" aria-hidden="true"></span>
        <% end %>
        </div></div>
    <% end %>


</div>

app/views/movies/show_genres.html.erb
<% @movies.each do |movie| %>


        <%= link_to movie do %>
    <%= image_tag(movie.photo.url) %><br>
        <%= movie.title %>
        <% end %>


<% end %>