config/routes.rb
Rails.application.routes.draw do

  resources :reviews

  root 'welcome#index'
  resources :movies

  resources :orders, except: [:new, :show]
  get '/genres' => 'movies#genres', as: :genres
  get '/movielist' => 'movies#show_genres'
  get '/orders/new/:id' => 'orders#new', as: :buy_movie
  get '/orders/cart/:id' => 'orders#show', as: :show_orders
  get '/cart/finalize/:sum' => 'orders#finalize', as: :finalize_order
  get '/cart/pay/:id' => 'orders#delegate_transaction', as: :delegate_order
  get '/watchlist' => 'orders#watchlist', as: :watch
  post '/watchlistpayu' => 'orders#watchlist'
  get '/theater/:movie' => 'orders#watch', as: :theater

  resources :orders

  devise_for :users, :controllers => { registrations: 'registrations' }

  resources :users

end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :movie, counter_cache: true
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_filter :authenticate_user!, only: [:new, :show, :finalize, :watch]
  before_action :set_order, only: [ :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  def finalize
    @user = User.find(current_user.id)
    @payment = params[:sum]


  end

  def watch
    user = User.find(current_user.id)
    orders = user.orders.where("status = true")
    movies_list = nil
    orders.each do |order|
      movies_list = order.movie_id if order.movie_id == params[:movie]
    end
    @movie = Movie.find(params[:movie])

  end

  def watchlist
    user = User.find(current_user.id)
    orders = user.orders
    if params[:status] == "OK"
      orders.each do |order|
        order.update_attribute(:status, true)
      end
      session[:orders_count] = 0
      session[:orders_sum] = 0
    end
    orders = user.orders.where("status = true")
    movies_ids = []
    orders.each do |order|
      movies_ids << order.movie_id
    end
    @movies = Movie.where(id: movies_ids)
  end

  def delegate_transaction

    user = User.find(current_user.id)
    orders = user.orders





    redirect_to show_orders_path, notice: 'Zapłaciłeś za filmy, gratulacje!'
  end

  # GET /orders/1
  # GET /orders/1.json
  def show

    @user = User.find(current_user.id)
    @orders = @user.orders

    session[:orders_sum] = @user.orders.where("status = false").sum("sum")
  end

  # GET /orders/new
  def new
    @order = Order.new
    @movie = Movie.find(params[:id])
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)


    respond_to do |format|
      if @order.save
        format.html { redirect_to root_path, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy

    session[:orders_count] -= 1

    @order.destroy
    respond_to do |format|
      format.html { redirect_to show_orders_path(current_user.id), notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params[:order].permit(:price, :user_id, :movie_id, :sum)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper

end

app/views/orders/_form.html.erb
Czy chcesz kupić film
<%= @movie.title %>
Cena: <%= @movie.price %>
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
      <%= f.hidden_field :movie_id, value: @movie.id%>
    <%= f.hidden_field :user_id, value: current_user.id if current_user%>
    <%= f.hidden_field :sum, value: @movie.price %>


  <div class="actions">
    <%= f.submit 'dodaj do koszyka' %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/finalize.html.erb
Masz zapłacić <%= @payment %>zł
<br>



<form action="https://ssl.dotpay.pl/" method="POST">

  <input type="hidden" name="id" value="72890" />
  <input type="hidden" name="pin" value="1234567887654321" />
  <input type="hidden" name="typ" value="0" />
  <input type="hidden" name="URL" value="https://young-everglades-3876.herokuapp.com/watchlistpayu" />
  <input type="hidden" name="kwota" value="<%= @payment %>" size="5" readonly />
  <input type="hidden" name="opis" value="Płatność użytkownika <%= @user.email %>" />
  <input type="hidden" name="blokuj" value="1" />
  <select name="kanal">

    <option value="20">Testowy</option>
  </select>
  <input type="submit" name="Zapłać / Pay" value="Zapłać / Pay" />
</form>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Orders</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form' %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>
<p>

  <% @orders.each do |order| %>
      <% if order.status == false %>
  <strong>Tytuł filmu</strong>
  <%= order.movie.title %>
</p>
      <p>Cena zamówienia:
      <%= order.movie.price %></p>
      <td><%= link_to 'Usuń zamówienie', order, method: :delete %><br><br>
      <% end %>
  <% end %>
  <td><%= link_to 'finalizuj zamówienie', finalize_order_path(session[:orders_sum]) if session[:orders_sum] > 0 %><br>
<% if session[:orders_sum] > 0%>
    Suma:<%= session[:orders_sum] %>zł
<% else %>
    Pusty koszyk :(

<% end %>

app/views/orders/watch.html.erb
<video width="640" height="480" controls>
  <source src="<%= @movie.video.url %>" type="video/mp4">
  Your browser does not support the video tag.
</video>

app/views/orders/watchlist.html.erb
<%=h '<div class="alert alert-dismissable alert-info">Transakcja przebiegła pomyślnie!</div>'.html_safe if params[:status] == "OK" %>
<%=h '<div class="alert alert-dismissable alert-warning">Coś poszło nie tak z płatnością!</div>'.html_safe if params[:status] == "FAIL" %>
<% @movies.each do |movie| %>
    <%= link_to movie.title, theater_path(movie.id) %> <br>
<% end %>

<div class="movie_window"></div>